import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiOutlineGithub, AiOutlineCopyright } from 'react-icons/ai';
import Image from "next/image";
import deved from "../public/Rohan parmar-img.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      < Head >
        <title>Rohan Parmar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head >

    <main className="bg-teal-50 px-10 md:px-20 lg:px-40 dark:bg-gray-900">
      <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons">Developed by RP</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />

            </li>
            <li>
              <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#"><button className="transition ease-in-out duration-700 ..."></button>Resume</a>
            </li>
          </ul>
        </nav>
        <div className=" text-center p-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Rohan Parmar</h2>
          <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-400">Web Developer and Designer</h3>
          <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto  dark:text-gray-400">Full stack developer having extensive knowlege of developing and designing web applications.
          </p>
        </div>
        
        <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96  dark:text-gray-400">
          <Image src={deved} layout="fill" objectFit="cover" alt={''} />
        </div>

      </section>

      <section  className="dark:text-gray-400">
        <div>
          <h3 className="text-3xl pt-10  dark:text-gray-400">Services I offer</h3>
          <p className="text-md py-2 leading-8 text-gray-800  dark:text-gray-400">
            Using the knowledge of developing and desinging different web applications, I can work efficiently for both <span className="text-teal-500">front</span> & <span className="text-teal-500">backend development</span> projects from scratch.
          </p>
          <p className="text-md py-2 leading-8 text-gray-800  dark:text-gray-400">
            I can work with different types of projects by my own or in a group in a fast-paced environmnet while <span className="text-teal-500">achieving goal</span> and meeting the <span className="text-teal-500">deadlines</span>.
          </p>
        </div>
        <div className=" lg:flex gap-10 dark:text-gray-400">
          <div className="text-center shadow-lg pd-10 rounded-xl my-10">
            <Image src={design} width={100} height={100} alt={''} />
            <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">Beautiful Designs</h3>
            <p className="py-2  dark:text-gray-400">
              creating elegant designs suited your needs following core design theory.
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1  dark:text-gray-400">Photoshop</p>
            <p className="text-gray-800 py-1  dark:text-gray-400">Illustrator</p>
            <p className="text-gray-800 py-1  dark:text-gray-400">Figma</p>

          </div>
          <div className="text-center shadow-lg pd-10 rounded-xl my-10">
            <Image src={code} width={100} height={100} alt={''} />
            <h3 className="text-lg font-medium pt-8 pb-2  dark:text-gray-400">Beautiful Designs</h3>
            <p className="py-2  dark:text-gray-400">
              creating elegant designs suited your needs following core design theory.
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1  dark:text-gray-400">Photoshop</p>
            <p className="text-gray-800 py-1  dark:text-gray-400">Illustrator</p>
            <p className="text-gray-800 py-1  dark:text-gray-400">Figma</p>

          </div>
          <div className="text-center shadow-lg pd-10 rounded-xl my-10  dark:text-gray-400">
            <Image src={consulting} width={100} height={100} alt={''} />
            <h3 className="text-lg font-medium pt-8 pb-2  dark:text-gray-400">Beautiful Designs</h3>
            <p className="py-2  dark:text-gray-400">
              creating elegant designs suited your needs following core design theory.
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1 dark:text-gray-400">Photoshop</p>
            <p className="text-gray-800 py-1  dark:text-gray-400">Illustrator</p>
            <p className="text-gray-800 py-1  dark:text-gray-400">Figma</p>

          </div>
        </div>
      </section>
      <section>
        <div>
          <h3 className="text-3xl py-1  dark:text-gray-400">Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-800  dark:text-gray-400">
            Using the knowledge of developing and desinging different web applications, I can work efficiently for both <span className="text-teal-500">front</span> & <span className="text-teal-500">backend development</span> projects from scratch.
          </p>
          <p className="text-md py-2 leading-8 text-gray-800  dark:text-gray-400">
            I can work with different types of projects by my own or in a group in a fast-paced environmnet while <span className="text-teal-500">achieving goal</span> and meeting the <span className="text-teal-500">deadlines</span>.
          </p>
        </div>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1">
            <Image
              src={web1}
              className="rounded-lg object-cover"
              width="100"
              height="100"
              layout="responsive"
              alt="Image"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web2}
              className="rounded-lg object-cover"
              width={"100"}
              height={"100"}
              layout="responsive"
              alt="Image"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web3}
              className="rounded-lg object-cover"
              width={"100"}
              height={"92"}
              layout="responsive"
              alt="Image"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web4}
              className="rounded-lg object-cover"
              width={"100"}
              height={"100"}
              layout="responsive"
              alt="Image"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web5}
              className="rounded-lg object-cover"
              width={"100"}
              height={"100"}
              layout="responsive"
              alt="Image"
            />
          </div>
          <div className="basis-1/3 flex-1">
            <Image
              src={web6}
              className="rounded-lg object-cover"
              width={"100"}
              height={"100"}
              layout="responsive"
              alt="Image"
            />
          </div>
        </div>
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 bg-white dark:text-gray-400 p-20 dark:bg-teal-600">
          <AiFillLinkedin />
          <AiOutlineGithub />
        </div>
      </section>

    </main>
    </div >

  );
}
